name: CompassNavigation
version: 1.6.2
description: This plugin allows you to create a usable compass that teleports you to specified locations.
website: http://dev.bukkit.org/bukkit-plugins/compass-navigation/
main: com.gmail.adamwoollen.CompassNavigation.CompassNavigation
authors: [xMRKIRO, Adzwooly]
softdepend: [Essentials, WorldEdit, WorldGuard, Vault, ProtocolLib]
commands:
  compassnav:
    description: Allows you to reload configuration and set up CompassNavigation ingame.
    aliases: [cn, compassnavigation]
    permission: compassnav.admin.help
    usage: "Usage: /compassnav help"
permissions:
  compassnav.*:
    description: Gives access to all CompassNavigation commands.
    default: op
    children:
      compassnav.use: true
      compassnav.admin: true
      compassnav.perks: true
  compassnav.use:
    description: Allows usage of the compass
    default: true
  compassnav.admin:
    description: Allows usage of CompassNavigation admin commands.
    default: op
    children:
      compassnav.admin.help: true
      compassnav.admin.reload: true
      compassnav.admin.setup: true
      compassnav.admin.sign: true
      compassnav.admin.update: true
  compassnav.admin.sign:
    description: Allows you to create and use Teleport signs.
    default: op
    children:
      compassnav.sign.create: true
      compassnav.sign.use: true
  compassnav.admin.help:
    description: Allows usage of /compassnav help.
    default: op
  compassnav.admin.reload:
    description: Allows usage of /compassnav reload.
    default: op
    children:
      compassnav.admin.help: true
  compassnav.admin.update:
    description: Allows you to get messages about CompassNavigation updates
    default: op
  compassnav.admin.setup:
    description: Allows usage of /compassnav setup.
    default: op
  compassnav.sign.create:
    description: Allows you to create Teleport signs.
    default: op
  compassnav.sign.use:
    description: Allows you to use Teleport signs.
    default: true
  compassnav.perks:
    description: Allows you to have several perks.
    default: op
    children:
      compassnav.perks.free: true
      compassnav.perks.useanywhere: true
  compassnav.perks.free:
    description: Allows you to bypass the economy and use slots for free.
    default: op
  compassnav.perks.useanywhere:
    description: Allows you to use the compass anywhere.
    default: op
    children:
      compassnav.perks.use.world: true
      compassnav.perks.use.region: true
  compassnav.perks.use.world:
    description: Allows you to use the compass in disabled worlds.
    default: op
  compassnav.perks.use.region:
    description: Allows you to use the compass in WorldGuard regions with compasses disabled.
    default: op